.\" $Id: readinfo_pp.1,v 1.1.1.1 2001/01/31 03:59:16 zarzycki Exp $
.TH READINFO_PP 1 $Date: 2001/01/31 03:59:16 $
.UC 4
.SH NAME
readinfo_pp \- pretty print a readinfo data file
.SH SYNOPSIS
.B readinfo
.SH DESCRIPTION
.PP
.B readinfo_pp
is a utility to pretty print a
.B readinfo
data file.
The program attempts to align columns in a readable format.
The input data file is read from stdin and the output is on stdout.
.SH
See also
.PP
.B readinfo(1)
